# Generated by Django 4.1.2 on 2022-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Complaint_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roomno', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('complaint', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('regno', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Outpass_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roomno', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('fromdate', models.CharField(max_length=100)),
                ('fromtime', models.CharField(max_length=100)),
                ('todate', models.CharField(max_length=100)),
                ('totime', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('regno', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roomno', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('complaint', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('regno', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outpass_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roomno', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('fromdate', models.CharField(max_length=100)),
                ('fromtime', models.CharField(max_length=100)),
                ('todate', models.CharField(max_length=100)),
                ('totime', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('regno', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
